Feature/encore added functionality
StackStorm-Exchange/stackstorm-orion pull request #6
Opened 2017-10-16 19:04 UTC by bishopbm1

Added action to query for agent information from orion. Added the needed agent settings into the node definitions. Added get agent id and delete agent functions that use the new agent actions. Also added the ability to delete nodes. Updated mode unmanage action to accept begin and end dates so that unmanage times and be set for future times and can be longer than max set time from the config. Added new tests for all new functions and actions.

2017-10-18 16:41 UTC, LindsayHill commented
Thanks for this @bishopbm1 - much appreciated. Would you mind bumping the version in `pack.yaml`, and adding an entry to CHANGES.md?

@jjm would you mind casting your eye over this since you wrote much of the original pack?

2017-10-19 09:29 UTC, jjm commented
@bishopbm1 Thank you for the PR, I'll get this reviewed today.

2017-10-19 14:14 UTC, bishopbm1 commented
@LindsayHill Thank you for taking a look at this. I made the changes that you requested.

@jjm Thank you for also taking a look at this!

2017-10-19 16:48 UTC, jjm requested changes
Overall very nice work, I would like to see slightly less code  around getting the `agent_id` duplicated in the actions instead of when getting an `orion_node` object.

With those small changes (and clarification on the `circle.yml changes), I'm very happy to merge this in.

2017-10-19 16:48 UTC, jjm commented on actions/agent_delete.yaml
> +    required: true
Would be nice to have a new line at the end of the file.

2017-10-19 16:48 UTC, jjm commented on actions/node_delete.yaml
> +    required: true
Would be nice to have a new line here too.

2017-10-19 16:48 UTC, jjm commented on circle.yml
> +    branches:
@emedvedev @Kami May be you can comment on this? I think this change should be reversed before merging, as it should this only run for the master branch in the StackStorm-Exchange org.

2017-10-19 16:48 UTC, jjm commented on actions/lib/actions.py
> +                orion_node.agent_id = data['results'][0]['AgentID']
This agent logic should really be in `get_node` and `agent` (and the other values) are populated without needing to pass around the `orion_node` object.

2017-10-19 16:48 UTC, jjm commented on actions/lib/node.py
> +        if agent_id is not None:
👍

2017-10-19 16:48 UTC, jjm commented on actions/lib/node.py
> +        else:
Is this `else` needed? They already default to these values.

2017-10-19 16:48 UTC, jjm commented on actions/node_delete.py
> +class NodeDelete(OrionBaseAction):
Nice to see this action added.

2017-10-19 16:48 UTC, jjm commented on actions/agent_delete.py
> +        orion_node = self.get_agent(orion_node)
See comments below about passing round the `orion_node` object.

2017-10-19 16:48 UTC, jjm commented on actions/lib/actions.py
> +    def get_agent(self, orion_node):
I would prefer if this function took `npm_id` as a parameter, instead of `orion_node`.

2017-10-20 17:46 UTC, bishopbm1 commented
@jjm I made all the changes you suggested. I also changed the circle.yml back to only build the master branch.

2017-10-24 20:55 UTC, jjm approved these changes
LGTM

2017-10-24 20:55 UTC, merged

2017-10-24 20:56 UTC, jjm commented
@bishopbm1 Thank you for the contrition!